//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_helper_181024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string course { get; set; }
        public Nullable<int> course_id { get; set; }
    }
}
